# Generated by Django 4.2.5 on 2024-09-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='name',
            new_name='receipes_name',
        ),
    ]
