# Generated by Django 4.2.5 on 2024-09-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_data_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_data',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students_data',
            name='file',
        ),
        migrations.RemoveField(
            model_name='students_data',
            name='image',
        ),
    ]
